//
// These are messages and services relating to a user feed, such as viewing and generating the feed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: proto/feed.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	common "github.com/kic/users/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//These are errors used to inform the client that is requesting a connection what the issue is.
//The variable names denote the issue.
type GenerateFeedError int32

const (
	// The constant representing when a user is not found.
	GenerateFeedError_USER_NOT_FOUND GenerateFeedError = 0
	// The constant representing when the feed has no more posts to show a user.
	GenerateFeedError_OUT_OF_POSTS GenerateFeedError = 1
)

// Enum value maps for GenerateFeedError.
var (
	GenerateFeedError_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "OUT_OF_POSTS",
	}
	GenerateFeedError_value = map[string]int32{
		"USER_NOT_FOUND": 0,
		"OUT_OF_POSTS":   1,
	}
)

func (x GenerateFeedError) Enum() *GenerateFeedError {
	p := new(GenerateFeedError)
	*p = x
	return p
}

func (x GenerateFeedError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateFeedError) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_feed_proto_enumTypes[0].Descriptor()
}

func (GenerateFeedError) Type() protoreflect.EnumType {
	return &file_proto_feed_proto_enumTypes[0]
}

func (x GenerateFeedError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateFeedError.Descriptor instead.
func (GenerateFeedError) EnumDescriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{0}
}

//
//Request to generate user feed for the user.
type GenerateFeedForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the user in the user database, used globally for identification.
	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *GenerateFeedForUserRequest) Reset() {
	*x = GenerateFeedForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateFeedForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFeedForUserRequest) ProtoMessage() {}

func (x *GenerateFeedForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFeedForUserRequest.ProtoReflect.Descriptor instead.
func (*GenerateFeedForUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateFeedForUserRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

//
//Response to a request for generating feed for the user.
type GenerateFeedForUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*GenerateFeedForUserResponse_FileInfo
	//	*GenerateFeedForUserResponse_Error
	Data isGenerateFeedForUserResponse_Data `protobuf_oneof:"data"`
}

func (x *GenerateFeedForUserResponse) Reset() {
	*x = GenerateFeedForUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateFeedForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFeedForUserResponse) ProtoMessage() {}

func (x *GenerateFeedForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFeedForUserResponse.ProtoReflect.Descriptor instead.
func (*GenerateFeedForUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{1}
}

func (m *GenerateFeedForUserResponse) GetData() isGenerateFeedForUserResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GenerateFeedForUserResponse) GetFileInfo() *common.File {
	if x, ok := x.GetData().(*GenerateFeedForUserResponse_FileInfo); ok {
		return x.FileInfo
	}
	return nil
}

func (x *GenerateFeedForUserResponse) GetError() GenerateFeedError {
	if x, ok := x.GetData().(*GenerateFeedForUserResponse_Error); ok {
		return x.Error
	}
	return GenerateFeedError_USER_NOT_FOUND
}

type isGenerateFeedForUserResponse_Data interface {
	isGenerateFeedForUserResponse_Data()
}

type GenerateFeedForUserResponse_FileInfo struct {
	// The file being pulled, consisting of the file name, file location, and metadata.
	FileInfo *common.File `protobuf:"bytes,1,opt,name=fileInfo,proto3,oneof"`
}

type GenerateFeedForUserResponse_Error struct {
	// The error occurring when the feed is generated.
	Error GenerateFeedError `protobuf:"varint,2,opt,name=error,proto3,enum=kic.feed.GenerateFeedError,oneof"`
}

func (*GenerateFeedForUserResponse_FileInfo) isGenerateFeedForUserResponse_Data() {}

func (*GenerateFeedForUserResponse_Error) isGenerateFeedForUserResponse_Data() {}

var File_proto_feed_proto protoreflect.FileDescriptor

var file_proto_feed_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x6b, 0x69, 0x63, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x1a, 0x12, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x34, 0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x8a, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x69, 0x63, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6b, 0x69, 0x63, 0x2e, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x2a, 0x39, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x46,
	0x65, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52,
	0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x53, 0x10, 0x01, 0x32, 0x6c,
	0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x64, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x24, 0x2e,
	0x6b, 0x69, 0x63, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x46, 0x65, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6b, 0x69, 0x63, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x14, 0x5a, 0x12,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_feed_proto_rawDescOnce sync.Once
	file_proto_feed_proto_rawDescData = file_proto_feed_proto_rawDesc
)

func file_proto_feed_proto_rawDescGZIP() []byte {
	file_proto_feed_proto_rawDescOnce.Do(func() {
		file_proto_feed_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_feed_proto_rawDescData)
	})
	return file_proto_feed_proto_rawDescData
}

var (
	file_proto_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_proto_feed_proto_msgTypes  = make([]protoimpl.MessageInfo, 2)
	file_proto_feed_proto_goTypes   = []interface{}{
		(GenerateFeedError)(0),              // 0: kic.feed.GenerateFeedError
		(*GenerateFeedForUserRequest)(nil),  // 1: kic.feed.GenerateFeedForUserRequest
		(*GenerateFeedForUserResponse)(nil), // 2: kic.feed.GenerateFeedForUserResponse
		(*common.File)(nil),                 // 3: kic.common.File
	}
)

var file_proto_feed_proto_depIdxs = []int32{
	3, // 0: kic.feed.GenerateFeedForUserResponse.fileInfo:type_name -> kic.common.File
	0, // 1: kic.feed.GenerateFeedForUserResponse.error:type_name -> kic.feed.GenerateFeedError
	1, // 2: kic.feed.Feed.GenerateFeedForUser:input_type -> kic.feed.GenerateFeedForUserRequest
	2, // 3: kic.feed.Feed.GenerateFeedForUser:output_type -> kic.feed.GenerateFeedForUserResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_feed_proto_init() }
func file_proto_feed_proto_init() {
	if File_proto_feed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_feed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateFeedForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_feed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateFeedForUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_feed_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GenerateFeedForUserResponse_FileInfo)(nil),
		(*GenerateFeedForUserResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_feed_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feed_proto_goTypes,
		DependencyIndexes: file_proto_feed_proto_depIdxs,
		EnumInfos:         file_proto_feed_proto_enumTypes,
		MessageInfos:      file_proto_feed_proto_msgTypes,
	}.Build()
	File_proto_feed_proto = out.File
	file_proto_feed_proto_rawDesc = nil
	file_proto_feed_proto_goTypes = nil
	file_proto_feed_proto_depIdxs = nil
}
